# GoReleaser configuration for mcp-server-planton.
#
# Produces multi-platform binaries:
#   mcp-server-planton_Darwin_arm64.tar.gz
#   mcp-server-planton_Linux_x86_64.tar.gz
#   ...
#
# Usage:
#   goreleaser release --clean

version: 2

project_name: mcp-server-planton

builds:
  - id: mcp-server-planton
    main: ./cmd/mcp-server-planton
    binary: mcp-server-planton
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: plantonhq
    name: mcp-server-planton
  draft: false
  prerelease: auto

sboms:
  - artifacts: archive

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
